package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestEnviarComprobante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "basic")
	private com.fogacoop.flujofogacoop.BasicDTO basic;
	@org.kie.api.definition.type.Label(value = "idPago")
	private java.lang.String idPago;
	@org.kie.api.definition.type.Label(value = "conjuntoComprobantes")
	private java.lang.String conjuntoComprobantes;
	@org.kie.api.definition.type.Label(value = "tokenAutenticatedBusiness")
	private com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness;

	public RequestEnviarComprobante() {
	}

	public com.fogacoop.flujofogacoop.BasicDTO getBasic() {
		return this.basic;
	}

	public void setBasic(com.fogacoop.flujofogacoop.BasicDTO basic) {
		this.basic = basic;
	}

	public java.lang.String getIdPago() {
		return this.idPago;
	}

	public void setIdPago(java.lang.String idPago) {
		this.idPago = idPago;
	}

	public java.lang.String getConjuntoComprobantes() {
		return this.conjuntoComprobantes;
	}

	public void setConjuntoComprobantes(java.lang.String conjuntoComprobantes) {
		this.conjuntoComprobantes = conjuntoComprobantes;
	}

	public com.fogacoop.flujofogacoop.TokenDTO getTokenAutenticatedBusiness() {
		return this.tokenAutenticatedBusiness;
	}

	public void setTokenAutenticatedBusiness(
			com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness) {
		this.tokenAutenticatedBusiness = tokenAutenticatedBusiness;
	}

	public RequestEnviarComprobante(com.fogacoop.flujofogacoop.BasicDTO basic,
			java.lang.String idPago, java.lang.String conjuntoComprobantes,
			com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness) {
		this.basic = basic;
		this.idPago = idPago;
		this.conjuntoComprobantes = conjuntoComprobantes;
		this.tokenAutenticatedBusiness = tokenAutenticatedBusiness;
	}

}